//! Conversions between client types and the Fynd RPC server's wire types.
//!
//! Uses `fynd-rpc-types` directly for the wire format, providing compile-time
//! compatibility guarantees with the server.

use fynd_rpc_types as wire;
use tycho_simulation::tycho_common::models::Address as TychoAddress;

use crate::error::{ErrorCode, FyndError};
use crate::types::{
    BackendKind, BlockInfo, HealthStatus, Order, OrderSide, OrderSolution, Quote, QuoteOptions,
    QuoteParams, Route, SolutionStatus, Swap,
};

// ============================================================================
// ADDRESS CONVERSION HELPERS
// ============================================================================

pub(crate) fn bytes_to_alloy_address(
    b: &bytes::Bytes,
) -> Result<alloy::primitives::Address, FyndError> {
    if b.len() != 20 {
        return Err(FyndError::Protocol(format!(
            "expected 20-byte address, got {} bytes",
            b.len()
        )));
    }
    let arr: [u8; 20] = b
        .as_ref()
        .try_into()
        .expect("length checked above");
    Ok(alloy::primitives::Address::from(arr))
}

/// Convert a client `bytes::Bytes` address to a tycho wire-format address.
fn bytes_to_tycho(b: &bytes::Bytes) -> Result<TychoAddress, FyndError> {
    if b.len() != 20 {
        return Err(FyndError::Protocol(format!(
            "expected 20-byte address, got {} bytes",
            b.len()
        )));
    }
    // hex_bytes::Bytes has From<bytes::Bytes>
    Ok(TychoAddress::from(b.clone()))
}

/// Convert a tycho wire-format address to a client `bytes::Bytes` address.
fn tycho_to_bytes(addr: TychoAddress) -> bytes::Bytes {
    // hex_bytes::Bytes has From<Bytes> -> bytes::Bytes, and inner field .0 is pub
    addr.0
}

// ============================================================================
// CLIENT TYPES → WIRE FORMAT
// ============================================================================

pub(crate) fn quote_params_to_wire(
    params: QuoteParams,
) -> Result<wire::SolutionRequest, FyndError> {
    let orders = params
        .orders
        .into_iter()
        .map(wire::Order::try_from)
        .collect::<Result<Vec<_>, _>>()?;
    Ok(wire::SolutionRequest { orders, options: params.options.into() })
}

impl TryFrom<Order> for wire::Order {
    type Error = FyndError;

    fn try_from(order: Order) -> Result<Self, Self::Error> {
        let token_in = bytes_to_tycho(order.token_in())?;
        let token_out = bytes_to_tycho(order.token_out())?;
        let sender = bytes_to_tycho(order.sender())?;
        let receiver = order
            .receiver()
            .map(bytes_to_tycho)
            .transpose()?;
        Ok(wire::Order {
            id: String::new(), // auto-generated by server via skip_deserializing
            token_in,
            token_out,
            amount: order.amount().clone(),
            side: order.side().into(),
            sender,
            receiver,
        })
    }
}

impl From<OrderSide> for wire::OrderSide {
    fn from(side: OrderSide) -> Self {
        match side {
            OrderSide::Sell => wire::OrderSide::Sell,
        }
    }
}

impl From<QuoteOptions> for wire::SolutionOptions {
    fn from(opts: QuoteOptions) -> Self {
        wire::SolutionOptions {
            timeout_ms: opts.timeout_ms,
            min_responses: opts.min_responses,
            max_gas: opts.max_gas,
        }
    }
}

// ============================================================================
// WIRE FORMAT → CLIENT TYPES
// ============================================================================

impl TryFrom<wire::Solution> for Quote {
    type Error = FyndError;

    fn try_from(wire: wire::Solution) -> Result<Self, Self::Error> {
        let orders = wire
            .orders
            .into_iter()
            .map(OrderSolution::try_from)
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Quote::new(orders, wire.total_gas_estimate, wire.solve_time_ms))
    }
}

impl TryFrom<wire::OrderSolution> for OrderSolution {
    type Error = FyndError;

    fn try_from(ws: wire::OrderSolution) -> Result<Self, Self::Error> {
        let status = SolutionStatus::from(ws.status);
        let route = ws
            .route
            .map(Route::try_from)
            .transpose()?;
        let block = BlockInfo::from(ws.block);
        Ok(OrderSolution::new(
            ws.order_id,
            status,
            BackendKind::Fynd,
            route,
            ws.amount_in,
            ws.amount_out,
            ws.gas_estimate,
            ws.price_impact_bps,
            block,
        ))
    }
}

impl From<wire::SolutionStatus> for SolutionStatus {
    fn from(ws: wire::SolutionStatus) -> Self {
        match ws {
            wire::SolutionStatus::Success => Self::Success,
            wire::SolutionStatus::NoRouteFound => Self::NoRouteFound,
            wire::SolutionStatus::InsufficientLiquidity => Self::InsufficientLiquidity,
            wire::SolutionStatus::Timeout => Self::Timeout,
            wire::SolutionStatus::NotReady => Self::NotReady,
        }
    }
}

impl TryFrom<wire::Route> for Route {
    type Error = FyndError;

    fn try_from(wr: wire::Route) -> Result<Self, Self::Error> {
        let swaps = wr
            .swaps
            .into_iter()
            .map(Swap::try_from)
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Route::new(swaps))
    }
}

impl TryFrom<wire::Swap> for Swap {
    type Error = FyndError;

    fn try_from(ws: wire::Swap) -> Result<Self, Self::Error> {
        let token_in = tycho_to_bytes(ws.token_in);
        let token_out = tycho_to_bytes(ws.token_out);
        Ok(Swap::new(
            ws.component_id,
            ws.protocol,
            token_in,
            token_out,
            ws.amount_in,
            ws.amount_out,
            ws.gas_estimate,
        ))
    }
}

impl From<wire::BlockInfo> for BlockInfo {
    fn from(wb: wire::BlockInfo) -> Self {
        BlockInfo::new(wb.number, wb.hash, wb.timestamp)
    }
}

impl From<wire::HealthStatus> for HealthStatus {
    fn from(wh: wire::HealthStatus) -> Self {
        HealthStatus::new(wh.healthy, wh.last_update_ms, wh.num_solver_pools)
    }
}

// ============================================================================
// ERROR CONVERSION
// ============================================================================

pub(crate) fn wire_error_to_fynd(we: wire::ErrorResponse) -> FyndError {
    let code = ErrorCode::from_server_code(&we.code);
    FyndError::Api { code, message: we.error }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bytes::Bytes;
    use num_bigint::BigUint;
    use tycho_simulation::tycho_common::models::Address as TychoAddress;

    fn make_tycho_addr(bytes: &[u8; 20]) -> TychoAddress {
        TychoAddress::from(Bytes::copy_from_slice(bytes))
    }

    fn sample_wire_swap() -> wire::Swap {
        wire::Swap {
            component_id: "pool-1".to_string(),
            protocol: "uniswap-v3".to_string(),
            token_in: make_tycho_addr(&[0xaa; 20]),
            token_out: make_tycho_addr(&[0xbb; 20]),
            amount_in: BigUint::from(100u32),
            amount_out: BigUint::from(99u32),
            gas_estimate: BigUint::from(50_000u32),
        }
    }

    fn sample_wire_block() -> wire::BlockInfo {
        wire::BlockInfo {
            number: 21_000_000,
            hash: "0xdeadbeef".to_string(),
            timestamp: 1_730_000_000,
        }
    }

    fn sample_wire_order_solution() -> wire::OrderSolution {
        wire::OrderSolution {
            order_id: "test-order-id".to_string(),
            status: wire::SolutionStatus::Success,
            route: None,
            amount_in: BigUint::from(1_000u32),
            amount_out: BigUint::from(999u32),
            gas_estimate: BigUint::from(100_000u32),
            price_impact_bps: Some(5),
            amount_out_net_gas: BigUint::from(998u32),
            block: sample_wire_block(),
        }
    }

    // -----------------------------------------------------------------------
    // bytes_to_alloy_address
    // -----------------------------------------------------------------------

    #[test]
    fn bytes_to_alloy_address_happy_path() {
        let b = Bytes::copy_from_slice(&[0xab; 20]);
        let addr = bytes_to_alloy_address(&b).unwrap();
        assert_eq!(addr.as_slice(), &[0xab; 20]);
    }

    #[test]
    fn bytes_to_alloy_address_wrong_length() {
        let b = Bytes::copy_from_slice(&[0xab; 4]);
        assert!(matches!(bytes_to_alloy_address(&b), Err(FyndError::Protocol(_))));
    }

    // -----------------------------------------------------------------------
    // Swap conversion
    // -----------------------------------------------------------------------

    #[test]
    fn swap_try_from_wire_happy_path() {
        let client_swap = Swap::try_from(sample_wire_swap()).unwrap();
        assert_eq!(client_swap.pool_id(), "pool-1");
        assert_eq!(client_swap.protocol(), "uniswap-v3");
        assert_eq!(client_swap.token_in(), &Bytes::copy_from_slice(&[0xaa; 20]));
        assert_eq!(client_swap.token_out(), &Bytes::copy_from_slice(&[0xbb; 20]));
        assert_eq!(client_swap.amount_in(), &BigUint::from(100u32));
        assert_eq!(client_swap.amount_out(), &BigUint::from(99u32));
        assert_eq!(client_swap.gas_estimate(), &BigUint::from(50_000u32));
    }

    // -----------------------------------------------------------------------
    // SolutionStatus conversion
    // -----------------------------------------------------------------------

    #[test]
    fn solution_status_all_variants() {
        use wire::SolutionStatus as Wire;
        assert!(matches!(SolutionStatus::from(Wire::Success), SolutionStatus::Success));
        assert!(matches!(SolutionStatus::from(Wire::NoRouteFound), SolutionStatus::NoRouteFound));
        assert!(matches!(
            SolutionStatus::from(Wire::InsufficientLiquidity),
            SolutionStatus::InsufficientLiquidity
        ));
        assert!(matches!(SolutionStatus::from(Wire::Timeout), SolutionStatus::Timeout));
        assert!(matches!(SolutionStatus::from(Wire::NotReady), SolutionStatus::NotReady));
    }

    // -----------------------------------------------------------------------
    // BlockInfo conversion
    // -----------------------------------------------------------------------

    #[test]
    fn block_info_from_wire() {
        let wire_block = sample_wire_block();
        let block = BlockInfo::from(wire_block);
        assert_eq!(block.number(), 21_000_000);
        assert_eq!(block.hash(), "0xdeadbeef");
        assert_eq!(block.timestamp(), 1_730_000_000);
    }

    // -----------------------------------------------------------------------
    // OrderSolution conversion
    // -----------------------------------------------------------------------

    #[test]
    fn order_solution_try_from_wire_drops_amount_out_net_gas_and_defaults_to_fynd() {
        let ws = sample_wire_order_solution();
        let solution = OrderSolution::try_from(ws).unwrap();
        assert_eq!(solution.order_id(), "test-order-id");
        assert!(matches!(solution.status(), SolutionStatus::Success));
        assert!(matches!(solution.backend(), BackendKind::Fynd));
        assert_eq!(solution.amount_in(), &BigUint::from(1_000u32));
        assert_eq!(solution.amount_out(), &BigUint::from(999u32));
        assert_eq!(solution.gas_estimate(), &BigUint::from(100_000u32));
        assert_eq!(solution.price_impact_bps(), Some(5));
        // token_out and receiver are left empty until populated by quote()
        assert!(solution.token_out().is_empty());
        assert!(solution.receiver().is_empty());
    }

    // -----------------------------------------------------------------------
    // Order → wire::Order conversion
    // -----------------------------------------------------------------------

    #[test]
    fn order_try_from_client_encodes_addresses_as_tycho() {
        let order = Order::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(1_000u32),
            OrderSide::Sell,
            Bytes::copy_from_slice(&[0xcc; 20]),
            None,
        );

        let wire_order = wire::Order::try_from(order).unwrap();
        // Verify token addresses are correctly represented as Tycho addresses
        assert_eq!(wire_order.token_in.0, Bytes::copy_from_slice(&[0xaa; 20]));
        assert_eq!(wire_order.token_out.0, Bytes::copy_from_slice(&[0xbb; 20]));
        assert_eq!(wire_order.sender.0, Bytes::copy_from_slice(&[0xcc; 20]));
        assert!(wire_order.receiver.is_none());
        assert_eq!(wire_order.amount, BigUint::from(1_000u32));
    }

    #[test]
    fn order_try_from_client_with_receiver() {
        let order = Order::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(1u32),
            OrderSide::Sell,
            Bytes::copy_from_slice(&[0xcc; 20]),
            Some(Bytes::copy_from_slice(&[0xdd; 20])),
        );

        let wire_order = wire::Order::try_from(order).unwrap();
        let receiver = wire_order.receiver.unwrap();
        assert_eq!(receiver.0, Bytes::copy_from_slice(&[0xdd; 20]));
    }

    #[test]
    fn order_try_from_client_invalid_address_length() {
        let order = Order::new(
            Bytes::copy_from_slice(&[0xaa; 4]), // wrong length
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(1u32),
            OrderSide::Sell,
            Bytes::copy_from_slice(&[0xcc; 20]),
            None,
        );
        assert!(matches!(wire::Order::try_from(order), Err(FyndError::Protocol(_))));
    }
}
