//! Conversions between client types and the Fynd RPC server's DTO types.
//!
//! Uses `fynd-rpc-types` directly for the DTO format, providing compile-time
//! compatibility guarantees with the server.

use fynd_rpc_types as dto;
use fynd_rpc_types::OrderQuote;
use tycho_simulation::tycho_common::models::Address as TychoAddress;

use crate::{
    error::{ErrorCode, FyndError},
    types::{
        BackendKind, BatchQuote, BlockInfo, EncodingOptions, HealthStatus, Order, OrderSide,
        PermitDetails, PermitSingle, Quote, QuoteOptions, QuoteParams, QuoteStatus, Route, Swap,
        Transaction, UserTransferType,
    },
};
// ============================================================================
// ADDRESS CONVERSION HELPERS
// ============================================================================

pub(crate) fn bytes_to_alloy_address(
    b: &bytes::Bytes,
) -> Result<alloy::primitives::Address, FyndError> {
    let arr: [u8; 20] = b.as_ref().try_into().map_err(|_| {
        FyndError::Protocol(format!("expected 20-byte address, got {} bytes", b.len()))
    })?;

    Ok(alloy::primitives::Address::from(arr))
}

/// Convert a client `bytes::Bytes` address to a tycho DTO-format address.
fn bytes_to_tycho(b: &bytes::Bytes) -> Result<TychoAddress, FyndError> {
    if b.len() != 20 {
        return Err(FyndError::Protocol(format!("expected 20-byte address, got {} bytes", b.len())));
    }
    // hex_bytes::Bytes has From<bytes::Bytes>
    Ok(TychoAddress::from(b.clone()))
}

/// Convert a tycho DTO-format address to a client `bytes::Bytes` address.
fn tycho_to_bytes(addr: TychoAddress) -> bytes::Bytes {
    // hex_bytes::Bytes has From<Bytes> -> bytes::Bytes, and inner field .0 is pub
    addr.0
}

// ============================================================================
// PRIMITIVE CONVERSIONS
// ============================================================================

/// Convert a [`num_bigint::BigUint`] to an [`alloy::primitives::U256`].
///
/// Serialises `n` as a big-endian byte string, right-pads into 32 bytes, and
/// constructs a `U256` from the resulting fixed-width representation.
pub(crate) fn biguint_to_u256(n: &num_bigint::BigUint) -> alloy::primitives::U256 {
    let bytes = n.to_bytes_be();
    let mut arr = [0u8; 32];
    let len = bytes.len().min(32);
    arr[32 - len..].copy_from_slice(&bytes[..len]);
    alloy::primitives::U256::from_be_bytes(arr)
}

// ============================================================================
// CLIENT TYPES → DTO FORMAT
// ============================================================================

pub(crate) fn quote_params_to_dto(params: QuoteParams) -> Result<dto::QuoteRequest, FyndError> {
    let order = dto::Order::try_from(params.order)?;
    let options = dto::QuoteOptions::try_from(params.options)?;
    Ok(dto::QuoteRequest { orders: vec![order], options })
}

impl TryFrom<Order> for dto::Order {
    type Error = FyndError;

    fn try_from(order: Order) -> Result<Self, Self::Error> {
        let token_in = bytes_to_tycho(order.token_in())?;
        let token_out = bytes_to_tycho(order.token_out())?;
        let sender = bytes_to_tycho(order.sender())?;
        let receiver = order
            .receiver()
            .map(bytes_to_tycho)
            .transpose()?;
        Ok(dto::Order {
            id: String::new(), // auto-generated by server via skip_deserializing
            token_in,
            token_out,
            amount: order.amount().clone(),
            side: order.side().into(),
            sender,
            receiver,
        })
    }
}

impl From<OrderSide> for dto::OrderSide {
    fn from(side: OrderSide) -> Self {
        match side {
            OrderSide::Sell => dto::OrderSide::Sell,
        }
    }
}

impl TryFrom<QuoteOptions> for dto::QuoteOptions {
    type Error = FyndError;

    fn try_from(opts: QuoteOptions) -> Result<Self, Self::Error> {
        Ok(dto::QuoteOptions {
            timeout_ms: opts.timeout_ms,
            min_responses: opts.min_responses,
            max_gas: opts.max_gas,
            encoding_options: opts.encoding_options.map(dto::EncodingOptions::try_from).transpose()?,
        })
    }
}

impl TryFrom<EncodingOptions> for dto::EncodingOptions {
    type Error = FyndError;

    fn try_from(opts: EncodingOptions) -> Result<Self, Self::Error> {
        use tycho_simulation::tycho_core::Bytes as TychoBytes;
        let permit = opts.permit.map(dto::PermitSingle::try_from).transpose()?;
        let permit2_signature = opts.permit2_signature.map(TychoBytes::from);
        Ok(dto::EncodingOptions {
            slippage: opts.slippage,
            transfer_type: opts.transfer_type.into(),
            permit,
            permit2_signature,
        })
    }
}

impl TryFrom<PermitSingle> for dto::PermitSingle {
    type Error = FyndError;

    fn try_from(p: PermitSingle) -> Result<Self, Self::Error> {
        use tycho_simulation::tycho_core::Bytes as TychoBytes;
        let details = dto::PermitDetails::try_from(p.details)?;
        let spender = TychoBytes::from(bytes_to_tycho(&p.spender)?.0);
        Ok(dto::PermitSingle { details, spender, sig_deadline: p.sig_deadline })
    }
}

impl TryFrom<PermitDetails> for dto::PermitDetails {
    type Error = FyndError;

    fn try_from(d: PermitDetails) -> Result<Self, Self::Error> {
        use tycho_simulation::tycho_core::Bytes as TychoBytes;
        let token = TychoBytes::from(bytes_to_tycho(&d.token)?.0);
        Ok(dto::PermitDetails { token, amount: d.amount, expiration: d.expiration, nonce: d.nonce })
    }
}

impl From<UserTransferType> for dto::UserTransferType {
    fn from(t: UserTransferType) -> Self {
        match t {
            UserTransferType::TransferFrom => dto::UserTransferType::TransferFrom,
            UserTransferType::TransferFromPermit2 => dto::UserTransferType::TransferFromPermit2,
            UserTransferType::None => dto::UserTransferType::None,
        }
    }
}

// ============================================================================
// DTO FORMAT → CLIENT TYPES
// ============================================================================

pub(crate) fn dto_to_quote(
    ds: OrderQuote,
    token_out: bytes::Bytes,
    receiver: bytes::Bytes,
) -> Result<Quote, FyndError> {
    let status = QuoteStatus::from(ds.status);
    let route = ds
        .route
        .map(Route::try_from)
        .transpose()?;
    let block = BlockInfo::from(ds.block);
    let transaction = ds.transaction.map(Transaction::from);
    Ok(Quote::new(
        ds.order_id,
        status,
        BackendKind::Fynd,
        route,
        ds.amount_in,
        ds.amount_out,
        ds.gas_estimate,
        ds.price_impact_bps,
        block,
        token_out,
        receiver,
        transaction,
    ))
}

impl From<dto::Transaction> for Transaction {
    fn from(dt: dto::Transaction) -> Self {
        Transaction::new(bytes::Bytes::copy_from_slice(dt.to.as_ref()), dt.value, dt.data)
    }
}

pub(crate) fn dto_to_batch_quote(
    ds: dto::Quote,
    token_out: bytes::Bytes,
    receiver: bytes::Bytes,
) -> Result<BatchQuote, FyndError> {
    let quotes = ds
        .orders
        .into_iter()
        .map(|os| dto_to_quote(os, token_out.clone(), receiver.clone()))
        .collect::<Result<Vec<Quote>, _>>()?;
    Ok(BatchQuote::new(quotes))
}

impl From<dto::QuoteStatus> for QuoteStatus {
    fn from(ds: dto::QuoteStatus) -> Self {
        match ds {
            dto::QuoteStatus::Success => Self::Success,
            dto::QuoteStatus::NoRouteFound => Self::NoRouteFound,
            dto::QuoteStatus::InsufficientLiquidity => Self::InsufficientLiquidity,
            dto::QuoteStatus::Timeout => Self::Timeout,
            dto::QuoteStatus::NotReady => Self::NotReady,
        }
    }
}

impl TryFrom<dto::Route> for Route {
    type Error = FyndError;

    fn try_from(dr: dto::Route) -> Result<Self, Self::Error> {
        let swaps = dr
            .swaps
            .into_iter()
            .map(Swap::try_from)
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Route::new(swaps))
    }
}

impl TryFrom<dto::Swap> for Swap {
    type Error = FyndError;

    fn try_from(ds: dto::Swap) -> Result<Self, Self::Error> {
        let token_in = tycho_to_bytes(ds.token_in);
        let token_out = tycho_to_bytes(ds.token_out);
        Ok(Swap::new(
            ds.component_id,
            ds.protocol,
            token_in,
            token_out,
            ds.amount_in,
            ds.amount_out,
            ds.gas_estimate,
            ds.split,
        ))
    }
}

impl From<dto::BlockInfo> for BlockInfo {
    fn from(db: dto::BlockInfo) -> Self {
        BlockInfo::new(db.number, db.hash, db.timestamp)
    }
}

impl From<dto::HealthStatus> for HealthStatus {
    fn from(dh: dto::HealthStatus) -> Self {
        HealthStatus::new(dh.healthy, dh.last_update_ms, dh.num_solver_pools, dh.derived_data_ready)
    }
}

// ============================================================================
// ERROR CONVERSION
// ============================================================================

pub(crate) fn dto_error_to_fynd(de: dto::ErrorResponse) -> FyndError {
    let code = ErrorCode::from_server_code(&de.code);
    FyndError::Api { code, message: de.error }
}

#[cfg(test)]
mod tests {
    use bytes::Bytes;
    use num_bigint::BigUint;
    use tycho_simulation::tycho_common::models::Address as TychoAddress;

    use super::*;

    fn make_tycho_addr(bytes: &[u8; 20]) -> TychoAddress {
        TychoAddress::from(Bytes::copy_from_slice(bytes))
    }

    fn sample_dto_swap() -> dto::Swap {
        dto::Swap {
            component_id: "pool-1".to_string(),
            protocol: "uniswap-v3".to_string(),
            token_in: make_tycho_addr(&[0xaa; 20]),
            token_out: make_tycho_addr(&[0xbb; 20]),
            amount_in: BigUint::from(100u32),
            amount_out: BigUint::from(99u32),
            gas_estimate: BigUint::from(50_000u32),
            split: 0.0,
        }
    }

    fn sample_dto_block() -> dto::BlockInfo {
        dto::BlockInfo {
            number: 21_000_000,
            hash: "0xdeadbeef".to_string(),
            timestamp: 1_730_000_000,
        }
    }

    fn sample_dto_order_quote() -> dto::OrderQuote {
        dto::OrderQuote {
            order_id: "test-order-id".to_string(),
            status: dto::QuoteStatus::Success,
            route: None,
            amount_in: BigUint::from(1_000u32),
            amount_out: BigUint::from(999u32),
            gas_estimate: BigUint::from(100_000u32),
            price_impact_bps: Some(5),
            amount_out_net_gas: BigUint::from(998u32),
            block: sample_dto_block(),
            gas_price: None,
            transaction: None,
        }
    }

    // -----------------------------------------------------------------------
    // biguint_to_u256
    // -----------------------------------------------------------------------

    #[test]
    fn biguint_to_u256_zero() {
        let result = biguint_to_u256(&BigUint::ZERO);
        assert_eq!(result, alloy::primitives::U256::ZERO);
    }

    #[test]
    fn biguint_to_u256_known_value() {
        let n = BigUint::from(0x1234_5678u64);
        let result = biguint_to_u256(&n);
        assert_eq!(result, alloy::primitives::U256::from(0x1234_5678u64));
    }

    // -----------------------------------------------------------------------
    // Transaction conversion
    // -----------------------------------------------------------------------

    #[test]
    fn transaction_from_dto() {
        use tycho_simulation::tycho_core::Bytes as TychoBytes;
        let router_bytes = vec![0x01u8; 20];
        let dto_tx = dto::Transaction {
            to: TychoBytes::from(Bytes::copy_from_slice(&router_bytes)),
            value: BigUint::ZERO,
            data: vec![0x12, 0x34],
        };
        let tx = Transaction::from(dto_tx);
        assert_eq!(tx.to().as_ref(), router_bytes.as_slice());
        assert_eq!(tx.value(), &BigUint::ZERO);
        assert_eq!(tx.data(), &[0x12, 0x34]);
    }

    // -----------------------------------------------------------------------
    // bytes_to_alloy_address
    // -----------------------------------------------------------------------

    #[test]
    fn bytes_to_alloy_address_happy_path() {
        let b = Bytes::copy_from_slice(&[0xab; 20]);
        let addr = bytes_to_alloy_address(&b).unwrap();
        assert_eq!(addr.as_slice(), &[0xab; 20]);
    }

    #[test]
    fn bytes_to_alloy_address_wrong_length() {
        let b = Bytes::copy_from_slice(&[0xab; 4]);
        assert!(matches!(bytes_to_alloy_address(&b), Err(FyndError::Protocol(_))));
    }

    // -----------------------------------------------------------------------
    // Swap conversion
    // -----------------------------------------------------------------------

    #[test]
    fn swap_try_from_dto_happy_path() {
        let client_swap = Swap::try_from(sample_dto_swap()).unwrap();
        assert_eq!(client_swap.component_id(), "pool-1");
        assert_eq!(client_swap.protocol(), "uniswap-v3");
        assert_eq!(client_swap.token_in(), &Bytes::copy_from_slice(&[0xaa; 20]));
        assert_eq!(client_swap.token_out(), &Bytes::copy_from_slice(&[0xbb; 20]));
        assert_eq!(client_swap.amount_in(), &BigUint::from(100u32));
        assert_eq!(client_swap.amount_out(), &BigUint::from(99u32));
        assert_eq!(client_swap.gas_estimate(), &BigUint::from(50_000u32));
    }

    // -----------------------------------------------------------------------
    // QuoteStatus conversion
    // -----------------------------------------------------------------------

    #[test]
    fn quote_status_all_variants() {
        use dto::QuoteStatus as Dto;
        assert!(matches!(QuoteStatus::from(Dto::Success), QuoteStatus::Success));
        assert!(matches!(QuoteStatus::from(Dto::NoRouteFound), QuoteStatus::NoRouteFound));
        assert!(matches!(
            QuoteStatus::from(Dto::InsufficientLiquidity),
            QuoteStatus::InsufficientLiquidity
        ));
        assert!(matches!(QuoteStatus::from(Dto::Timeout), QuoteStatus::Timeout));
        assert!(matches!(QuoteStatus::from(Dto::NotReady), QuoteStatus::NotReady));
    }

    // -----------------------------------------------------------------------
    // BlockInfo conversion
    // -----------------------------------------------------------------------

    #[test]
    fn block_info_from_dto() {
        let dto_block = sample_dto_block();
        let block = BlockInfo::from(dto_block);
        assert_eq!(block.number(), 21_000_000);
        assert_eq!(block.hash(), "0xdeadbeef");
        assert_eq!(block.timestamp(), 1_730_000_000);
    }

    // -----------------------------------------------------------------------
    // OrderQuote conversion
    // -----------------------------------------------------------------------

    #[test]
    fn quote_try_from_dto_drops_amount_out_net_gas_and_defaults_to_fynd() {
        let ds = sample_dto_order_quote();
        let quote = dto_to_quote(ds, Bytes::new(), Bytes::new()).unwrap();
        assert_eq!(quote.order_id(), "test-order-id");
        assert!(matches!(quote.status(), QuoteStatus::Success));
        assert!(matches!(quote.backend(), BackendKind::Fynd));
        assert_eq!(quote.amount_in(), &BigUint::from(1_000u32));
        assert_eq!(quote.amount_out(), &BigUint::from(999u32));
        assert_eq!(quote.gas_estimate(), &BigUint::from(100_000u32));
        assert_eq!(quote.price_impact_bps(), Some(5));
        // token_out and receiver are left empty until populated by quote()
        assert!(quote.token_out().is_empty());
        assert!(quote.receiver().is_empty());
    }

    // -----------------------------------------------------------------------
    // Order → dto::Order conversion
    // -----------------------------------------------------------------------

    #[test]
    fn order_try_from_client_encodes_addresses_as_tycho() {
        let order = Order::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(1_000u32),
            OrderSide::Sell,
            Bytes::copy_from_slice(&[0xcc; 20]),
            None,
        );

        let dto_order = dto::Order::try_from(order).unwrap();
        // Verify token addresses are correctly represented as Tycho addresses
        assert_eq!(dto_order.token_in.0, Bytes::copy_from_slice(&[0xaa; 20]));
        assert_eq!(dto_order.token_out.0, Bytes::copy_from_slice(&[0xbb; 20]));
        assert_eq!(dto_order.sender.0, Bytes::copy_from_slice(&[0xcc; 20]));
        assert!(dto_order.receiver.is_none());
        assert_eq!(dto_order.amount, BigUint::from(1_000u32));
    }

    #[test]
    fn order_try_from_client_with_receiver() {
        let order = Order::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(1u32),
            OrderSide::Sell,
            Bytes::copy_from_slice(&[0xcc; 20]),
            Some(Bytes::copy_from_slice(&[0xdd; 20])),
        );

        let dto_order = dto::Order::try_from(order).unwrap();
        let receiver = dto_order.receiver.unwrap();
        assert_eq!(receiver.0, Bytes::copy_from_slice(&[0xdd; 20]));
    }

    #[test]
    fn order_try_from_client_invalid_address_length() {
        let order = Order::new(
            Bytes::copy_from_slice(&[0xaa; 4]), // wrong length
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(1u32),
            OrderSide::Sell,
            Bytes::copy_from_slice(&[0xcc; 20]),
            None,
        );
        assert!(matches!(dto::Order::try_from(order), Err(FyndError::Protocol(_))));
    }

    // -----------------------------------------------------------------------
    // UserTransferType mapping
    // -----------------------------------------------------------------------

    #[test]
    fn user_transfer_type_permit2_maps_correctly() {
        let result = dto::UserTransferType::from(UserTransferType::TransferFromPermit2);
        assert!(matches!(result, dto::UserTransferType::TransferFromPermit2));
    }

    #[test]
    fn user_transfer_type_none_maps_correctly() {
        let result = dto::UserTransferType::from(UserTransferType::None);
        assert!(matches!(result, dto::UserTransferType::None));
    }

    // -----------------------------------------------------------------------
    // PermitDetails TryFrom
    // -----------------------------------------------------------------------

    #[test]
    fn permit_details_try_from_happy_path() {
        let details = PermitDetails::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            BigUint::from(1_000u32),
            BigUint::from(9_999_999u32),
            BigUint::from(0u32),
        );
        let dto_details = dto::PermitDetails::try_from(details).unwrap();
        assert_eq!(dto_details.token.as_ref(), &[0xaa; 20]);
        assert_eq!(dto_details.amount, BigUint::from(1_000u32));
        assert_eq!(dto_details.expiration, BigUint::from(9_999_999u32));
        assert_eq!(dto_details.nonce, BigUint::from(0u32));
    }

    #[test]
    fn permit_details_try_from_invalid_token() {
        let details = PermitDetails::new(
            Bytes::copy_from_slice(&[0xaa; 4]), // wrong length
            BigUint::from(1u32),
            BigUint::from(1u32),
            BigUint::from(0u32),
        );
        assert!(matches!(dto::PermitDetails::try_from(details), Err(FyndError::Protocol(_))));
    }

    // -----------------------------------------------------------------------
    // PermitSingle TryFrom
    // -----------------------------------------------------------------------

    #[test]
    fn permit_single_try_from_happy_path() {
        let details = PermitDetails::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            BigUint::from(500u32),
            BigUint::from(1_000_000u32),
            BigUint::from(1u32),
        );
        let permit = PermitSingle::new(
            details,
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(2_000_000u32),
        );
        let dto_permit = dto::PermitSingle::try_from(permit).unwrap();
        assert_eq!(dto_permit.spender.as_ref(), &[0xbb; 20]);
        assert_eq!(dto_permit.sig_deadline, BigUint::from(2_000_000u32));
        assert_eq!(dto_permit.details.amount, BigUint::from(500u32));
    }

    // -----------------------------------------------------------------------
    // EncodingOptions TryFrom with permit2
    // -----------------------------------------------------------------------

    #[test]
    fn encoding_options_try_from_with_permit2() {
        use crate::types::{EncodingOptions, PermitDetails, PermitSingle};

        let details = PermitDetails::new(
            Bytes::copy_from_slice(&[0xaa; 20]),
            BigUint::from(1_000u32),
            BigUint::from(9_999_999u32),
            BigUint::from(0u32),
        );
        let permit = PermitSingle::new(
            details,
            Bytes::copy_from_slice(&[0xbb; 20]),
            BigUint::from(9_999_999u32),
        );
        let sig = Bytes::copy_from_slice(&[0xcc; 65]);
        let opts = EncodingOptions::new(0.005).with_permit2(permit, sig.clone()).unwrap();

        let dto_opts = dto::EncodingOptions::try_from(opts).unwrap();
        assert!(matches!(dto_opts.transfer_type, dto::UserTransferType::TransferFromPermit2));
        assert!(dto_opts.permit.is_some());
        assert_eq!(dto_opts.permit2_signature.as_ref().unwrap().as_ref(), sig.as_ref());
    }
}
