{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fynd.fullname" . }}-ext-secret
  labels:
    {{- include "fynd.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "2m" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | default "default" }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "fynd.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: RPC_URL
      remoteRef:
        key: {{ .Values.externalSecrets.awsSecretName }}
        property: RPC_URL
    - secretKey: TYCHO_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.awsSecretName }}
        property: TYCHO_API_KEY
{{- end }}
