/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/health - Health check endpoint.
         * @description Returns the current health status of the service.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/solve - Submit a solve request.
         * @description Accepts a `SolutionRequest` and returns a `Solution` with the best routes found, or an error
         *     if the request could not be filled.
         *
         *     # Errors
         *
         *     - 400 Bad Request: Invalid request format
         *     - 422 Unprocessable Entity: No routes found
         *     - 503 Service Unavailable: Queue full or service overloaded
         *     - 504 Gateway Timeout: Solve timeout
         */
        post: operations["solve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Block information at which a quote was computed.
         *
         *     Quotes are only valid for the block at which they were computed. Market
         *     conditions may change in subsequent blocks.
         */
        BlockInfo: {
            /**
             * @description Block hash as a hex string.
             * @example 0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd
             */
            hash: string;
            /**
             * Format: int64
             * @description Block number.
             * @example 21000000
             */
            number: number;
            /**
             * Format: int64
             * @description Block timestamp in Unix seconds.
             * @example 1730000000
             */
            timestamp: number;
        };
        /** @description Error response body. */
        ErrorResponse: {
            /** @example BAD_REQUEST */
            code: string;
            details?: unknown;
            /** @example bad request: no orders provided */
            error: string;
        };
        /** @description Health check response. */
        HealthStatus: {
            /**
             * @description Whether the service is healthy.
             * @example true
             */
            healthy: boolean;
            /**
             * Format: int64
             * @description Time since last market update in milliseconds.
             * @example 1250
             */
            last_update_ms: number;
            /**
             * @description Number of active solver pools.
             * @example 2
             */
            num_solver_pools: number;
        };
        /**
         * @description A single swap order to be solved.
         *
         *     An order specifies an intent to swap one token for another.
         */
        Order: {
            /**
             * @description Amount to swap, interpreted according to `side` (in token units, as decimal string).
             * @example 1000000000000000000
             */
            amount: string;
            /**
             * @description Address that will receive the output tokens.
             *
             *     Defaults to `sender` if not specified.
             * @example 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
             */
            receiver?: string | null;
            /**
             * @description Address that will send the input tokens.
             * @example 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
             */
            sender: string;
            /** @description Whether this is a sell (exact input) or buy (exact output) order. */
            side: components["schemas"]["OrderSide"];
            /**
             * @description Input token address (the token being sold).
             * @example 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
             */
            token_in: string;
            /**
             * @description Output token address (the token being bought).
             * @example 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
             */
            token_out: string;
        };
        /**
         * @description Specifies the side of an order: sell (exact input) or buy (exact output).
         *
         *     Currently only `Sell` is supported. `Buy` will be added in a future version.
         * @enum {string}
         */
        OrderSide: "sell";
        /**
         * @description Solution for a single [`Order`].
         *
         *     Contains the route to execute (if found), along with expected amounts,
         *     gas estimates, and status information.
         */
        OrderSolution: {
            /**
             * @description Amount of input token (in token units, as decimal string).
             * @example 1000000000000000000
             */
            amount_in: string;
            /**
             * @description Amount of output token (in token units, as decimal string).
             * @example 3500000000
             */
            amount_out: string;
            /**
             * @description Amount out minus gas cost in output token terms.
             *     Used by OrderManager to compare solutions from different solvers.
             * @example 3498000000
             */
            amount_out_net_gas: string;
            /** @description Block at which this quote was computed. */
            block: components["schemas"]["BlockInfo"];
            /**
             * @description Estimated gas cost for executing this route (as decimal string).
             * @example 150000
             */
            gas_estimate: string;
            /**
             * @description ID of the order this solution corresponds to.
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            order_id: string;
            /**
             * Format: int32
             * @description Price impact in basis points (1 bip = 0.01%).
             */
            price_impact_bps?: number | null;
            route?: null | components["schemas"]["Route"];
            /** @description Status indicating whether a route was found. */
            status: components["schemas"]["SolutionStatus"];
        };
        /**
         * @description A route consisting of one or more sequential swaps.
         *
         *     A route describes the path through liquidity pools to execute a swap.
         *     For multi-hop swaps, the output of each swap becomes the input of the next.
         */
        Route: {
            /** @description Ordered sequence of swaps to execute. */
            swaps: components["schemas"]["Swap"][];
        };
        /**
         * @description Complete solution for a [`SolutionRequest`].
         *
         *     Contains a solution for each order in the request, along with aggregate
         *     gas estimates and timing information.
         */
        Solution: {
            /** @description Solutions for each order, in the same order as the request. */
            orders: components["schemas"]["OrderSolution"][];
            /**
             * Format: int64
             * @description Time taken to compute this solution, in milliseconds.
             * @example 12
             */
            solve_time_ms: number;
            /**
             * @description Total estimated gas for executing all swaps (as decimal string).
             * @example 150000
             */
            total_gas_estimate: string;
        };
        /** @description Options to customize the solving behavior. */
        SolutionOptions: {
            /**
             * @description Maximum gas cost allowed for a solution. Solutions exceeding this are filtered out.
             * @example 500000
             */
            max_gas?: string | null;
            /**
             * @description Minimum number of solver responses to wait for before returning.
             *     If `None` or `0`, waits for all solvers to respond (or timeout).
             *
             *     Use the `/health` endpoint to check `num_solver_pools` before setting this value.
             *     Values exceeding the number of active solver pools are clamped internally.
             */
            min_responses?: number | null;
            /**
             * Format: int64
             * @description Timeout in milliseconds. If `None`, uses server default.
             * @example 2000
             */
            timeout_ms?: number | null;
        };
        /** @description Request to solve one or more swap orders. */
        SolutionRequest: {
            /** @description Optional solving parameters that apply to all orders. */
            options?: components["schemas"]["SolutionOptions"];
            /** @description Orders to solve. */
            orders: components["schemas"]["Order"][];
        };
        /**
         * @description Status of an order solution.
         * @enum {string}
         */
        SolutionStatus: "success" | "no_route_found" | "insufficient_liquidity" | "timeout" | "not_ready";
        /**
         * @description A single swap within a route.
         *
         *     Represents an atomic swap on a specific liquidity pool (component).
         */
        Swap: {
            /**
             * @description Amount of input token (in token units, as decimal string).
             * @example 1000000000000000000
             */
            amount_in: string;
            /**
             * @description Amount of output token (in token units, as decimal string).
             * @example 3500000000
             */
            amount_out: string;
            /**
             * @description Identifier of the liquidity pool component.
             * @example 0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc
             */
            component_id: string;
            /**
             * @description Estimated gas cost for this swap (as decimal string).
             * @example 150000
             */
            gas_estimate: string;
            /**
             * @description Protocol system identifier (e.g., "uniswap_v2", "uniswap_v3", "vm:balancer").
             * @example uniswap_v2
             */
            protocol: string;
            /**
             * @description Input token address.
             * @example 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
             */
            token_in: string;
            /**
             * @description Output token address.
             * @example 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
             */
            token_out: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Data stale */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    solve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolutionRequest"];
            };
        };
        responses: {
            /** @description Solve completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Solution"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No route found */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Solve timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
