//! Data Transfer Objects (DTOs) for the Fynd RPC HTTP API.
//!
//! This crate contains only the wire-format types shared between the Fynd RPC server
//! (`fynd-rpc`) and its clients (`fynd-client`). It has no server-side infrastructure
//! dependencies (no actix-web, no server logic).
//!
//! Enable the `openapi` feature to derive `utoipa::ToSchema` on all types for use in
//! API documentation generation.

use num_bigint::BigUint;
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};
use tycho_simulation::tycho_common::models::Address;
use uuid::Uuid;

// ============================================================================
// REQUEST TYPES
// ============================================================================

/// Request to solve one or more swap orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct SolutionRequest {
    /// Orders to solve.
    pub orders: Vec<Order>,
    /// Optional solving parameters that apply to all orders.
    #[serde(default)]
    pub options: SolutionOptions,
}

/// Options to customize the solving behavior.
#[serde_as]
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct SolutionOptions {
    /// Timeout in milliseconds. If `None`, uses server default.
    #[cfg_attr(feature = "openapi", schema(example = 2000))]
    pub timeout_ms: Option<u64>,
    /// Minimum number of solver responses to wait for before returning.
    /// If `None` or `0`, waits for all solvers to respond (or timeout).
    ///
    /// Use the `/health` endpoint to check `num_solver_pools` before setting this value.
    /// Values exceeding the number of active solver pools are clamped internally.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_responses: Option<usize>,
    /// Maximum gas cost allowed for a solution. Solutions exceeding this are filtered out.
    #[serde_as(as = "Option<DisplayFromStr>")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(feature = "openapi", schema(value_type = Option<String>, example = "500000"))]
    pub max_gas: Option<BigUint>,
}

// ============================================================================
// RESPONSE TYPES
// ============================================================================

/// Complete solution for a [`SolutionRequest`].
///
/// Contains a solution for each order in the request, along with aggregate
/// gas estimates and timing information.
#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct Solution {
    /// Solutions for each order, in the same order as the request.
    pub orders: Vec<OrderSolution>,
    /// Total estimated gas for executing all swaps (as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(feature = "openapi", schema(value_type = String, example = "150000"))]
    pub total_gas_estimate: BigUint,
    /// Time taken to compute this solution, in milliseconds.
    #[cfg_attr(feature = "openapi", schema(example = 12))]
    pub solve_time_ms: u64,
}

/// A single swap order to be solved.
///
/// An order specifies an intent to swap one token for another.
#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct Order {
    /// Unique identifier for this order.
    ///
    /// Auto-generated by the API.
    #[serde(default = "generate_order_id", skip_deserializing)]
    pub id: String,
    /// Input token address (the token being sold).
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2")
    )]
    pub token_in: Address,
    /// Output token address (the token being bought).
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")
    )]
    pub token_out: Address,
    /// Amount to swap, interpreted according to `side` (in token units, as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "1000000000000000000")
    )]
    pub amount: BigUint,
    /// Whether this is a sell (exact input) or buy (exact output) order.
    pub side: OrderSide,
    /// Address that will send the input tokens.
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045")
    )]
    pub sender: Address,
    /// Address that will receive the output tokens.
    ///
    /// Defaults to `sender` if not specified.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = Option<String>, example = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045")
    )]
    pub receiver: Option<Address>,
}

/// Specifies the side of an order: sell (exact input) or buy (exact output).
///
/// Currently only `Sell` is supported. `Buy` will be added in a future version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum OrderSide {
    /// Sell exactly the specified amount of the input token.
    Sell,
}

/// Internal wrapper used by workers when returning a solution.
///
/// This wraps [`OrderSolution`] with per-worker timing information.
/// The `solve_time_ms` here is the time taken by an individual worker/algorithm,
/// not the total OrderManager orchestration time (which is in [`Solution`]).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct SingleOrderSolution {
    /// The solution for the order.
    pub order: OrderSolution,
    /// Time taken by this specific worker to compute the solution, in milliseconds.
    pub solve_time_ms: u64,
}

/// Solution for a single [`Order`].
///
/// Contains the route to execute (if found), along with expected amounts,
/// gas estimates, and status information.
#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct OrderSolution {
    /// ID of the order this solution corresponds to.
    #[cfg_attr(feature = "openapi", schema(example = "f47ac10b-58cc-4372-a567-0e02b2c3d479"))]
    pub order_id: String,
    /// Status indicating whether a route was found.
    pub status: SolutionStatus,
    /// The route to execute, if a valid route was found.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<Route>,
    /// Amount of input token (in token units, as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "1000000000000000000")
    )]
    pub amount_in: BigUint,
    /// Amount of output token (in token units, as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(feature = "openapi", schema(value_type = String, example = "3500000000"))]
    pub amount_out: BigUint,
    /// Estimated gas cost for executing this route (as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(feature = "openapi", schema(value_type = String, example = "150000"))]
    pub gas_estimate: BigUint,
    /// Price impact in basis points (1 bip = 0.01%).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_impact_bps: Option<i32>,
    /// Amount out minus gas cost in output token terms.
    /// Used by OrderManager to compare solutions from different solvers.
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(feature = "openapi", schema(value_type = String, example = "3498000000"))]
    pub amount_out_net_gas: BigUint,
    /// Block at which this quote was computed.
    pub block: BlockInfo,
}

/// Status of an order solution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum SolutionStatus {
    /// A valid route was found.
    Success,
    /// No route exists between the specified tokens.
    NoRouteFound,
    /// A route exists but available liquidity is insufficient.
    InsufficientLiquidity,
    /// The solver timed out before finding a route.
    Timeout,
    /// No solver workers are ready (e.g., market data not yet initialized).
    NotReady,
}

/// Block information at which a quote was computed.
///
/// Quotes are only valid for the block at which they were computed. Market
/// conditions may change in subsequent blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct BlockInfo {
    /// Block number.
    #[cfg_attr(feature = "openapi", schema(example = 21000000))]
    pub number: u64,
    /// Block hash as a hex string.
    #[cfg_attr(
        feature = "openapi",
        schema(example = "0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd")
    )]
    pub hash: String,
    /// Block timestamp in Unix seconds.
    #[cfg_attr(feature = "openapi", schema(example = 1730000000))]
    pub timestamp: u64,
}

// ============================================================================
// ROUTE & SWAP TYPES
// ============================================================================

/// A route consisting of one or more sequential swaps.
///
/// A route describes the path through liquidity pools to execute a swap.
/// For multi-hop swaps, the output of each swap becomes the input of the next.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct Route {
    /// Ordered sequence of swaps to execute.
    pub swaps: Vec<Swap>,
}

/// A single swap within a route.
///
/// Represents an atomic swap on a specific liquidity pool (component).
#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct Swap {
    /// Identifier of the liquidity pool component.
    #[cfg_attr(
        feature = "openapi",
        schema(example = "0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc")
    )]
    pub component_id: String,
    /// Protocol system identifier (e.g., "uniswap_v2", "uniswap_v3", "vm:balancer").
    #[cfg_attr(feature = "openapi", schema(example = "uniswap_v2"))]
    pub protocol: String,
    /// Input token address.
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2")
    )]
    pub token_in: Address,
    /// Output token address.
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")
    )]
    pub token_out: Address,
    /// Amount of input token (in token units, as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(
        feature = "openapi",
        schema(value_type = String, example = "1000000000000000000")
    )]
    pub amount_in: BigUint,
    /// Amount of output token (in token units, as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(feature = "openapi", schema(value_type = String, example = "3500000000"))]
    pub amount_out: BigUint,
    /// Estimated gas cost for this swap (as decimal string).
    #[serde_as(as = "DisplayFromStr")]
    #[cfg_attr(feature = "openapi", schema(value_type = String, example = "150000"))]
    pub gas_estimate: BigUint,
}

// ============================================================================
// HEALTH CHECK TYPES
// ============================================================================

/// Health check response.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct HealthStatus {
    /// Whether the service is healthy.
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub healthy: bool,
    /// Time since last market update in milliseconds.
    #[cfg_attr(feature = "openapi", schema(example = 1250))]
    pub last_update_ms: u64,
    /// Number of active solver pools.
    #[cfg_attr(feature = "openapi", schema(example = 2))]
    pub num_solver_pools: usize,
}

/// Error response body.
#[derive(Debug, Serialize, Deserialize)]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
pub struct ErrorResponse {
    #[cfg_attr(feature = "openapi", schema(example = "bad request: no orders provided"))]
    pub error: String,
    #[cfg_attr(feature = "openapi", schema(example = "BAD_REQUEST"))]
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

// ============================================================================
// PRIVATE HELPERS
// ============================================================================

/// Generates a unique order ID using UUID v4.
fn generate_order_id() -> String {
    Uuid::new_v4().to_string()
}

// ============================================================================
// CONVERSIONS: fynd-core integration (feature = "core")
// ============================================================================

/// Conversions between DTO types and [`fynd_core`] domain types.
///
/// - [`From<fynd_core::X>`] for DTO types handles the Core → DTO direction.
/// - [`Into<fynd_core::X>`] for DTO types handles the DTO → Core direction. (`From` cannot be used
///   in that direction: `fynd_core` types are external, so implementing `From<DTO>` on them would
///   violate the orphan rule.)
#[cfg(feature = "core")]
mod conversions {
    use super::*;

    // -------------------------------------------------------------------------
    // DTO → Core
    // -------------------------------------------------------------------------

    impl Into<fynd_core::SolutionRequest> for SolutionRequest {
        fn into(self) -> fynd_core::SolutionRequest {
            fynd_core::SolutionRequest {
                orders: self
                    .orders
                    .into_iter()
                    .map(Into::into)
                    .collect(),
                options: self.options.into(),
            }
        }
    }

    impl Into<fynd_core::SolutionOptions> for SolutionOptions {
        fn into(self) -> fynd_core::SolutionOptions {
            fynd_core::SolutionOptions {
                timeout_ms: self.timeout_ms,
                min_responses: self.min_responses,
                max_gas: self.max_gas,
                encoding_options: None,
            }
        }
    }

    impl Into<fynd_core::Order> for Order {
        fn into(self) -> fynd_core::Order {
            fynd_core::Order {
                id: self.id,
                token_in: self.token_in,
                token_out: self.token_out,
                amount: self.amount,
                side: self.side.into(),
                sender: self.sender,
                receiver: self.receiver,
            }
        }
    }

    impl Into<fynd_core::OrderSide> for OrderSide {
        fn into(self) -> fynd_core::OrderSide {
            match self {
                OrderSide::Sell => fynd_core::OrderSide::Sell,
            }
        }
    }

    // -------------------------------------------------------------------------
    // Core → DTO
    // -------------------------------------------------------------------------

    impl From<fynd_core::Solution> for Solution {
        fn from(core: fynd_core::Solution) -> Self {
            Solution {
                orders: core
                    .orders
                    .into_iter()
                    .map(Into::into)
                    .collect(),
                total_gas_estimate: core.total_gas_estimate,
                solve_time_ms: core.solve_time_ms,
            }
        }
    }

    impl From<fynd_core::OrderSolution> for OrderSolution {
        fn from(core: fynd_core::OrderSolution) -> Self {
            OrderSolution {
                order_id: core.order_id,
                status: core.status.into(),
                route: core.route.map(Into::into),
                amount_in: core.amount_in,
                amount_out: core.amount_out,
                gas_estimate: core.gas_estimate,
                price_impact_bps: core.price_impact_bps,
                amount_out_net_gas: core.amount_out_net_gas,
                block: core.block.into(),
            }
        }
    }

    impl From<fynd_core::SolutionStatus> for SolutionStatus {
        fn from(core: fynd_core::SolutionStatus) -> Self {
            match core {
                fynd_core::SolutionStatus::Success => SolutionStatus::Success,
                fynd_core::SolutionStatus::NoRouteFound => SolutionStatus::NoRouteFound,
                fynd_core::SolutionStatus::InsufficientLiquidity => {
                    SolutionStatus::InsufficientLiquidity
                }
                fynd_core::SolutionStatus::Timeout => SolutionStatus::Timeout,
                fynd_core::SolutionStatus::NotReady => SolutionStatus::NotReady,
            }
        }
    }

    impl From<fynd_core::BlockInfo> for BlockInfo {
        fn from(core: fynd_core::BlockInfo) -> Self {
            BlockInfo { number: core.number, hash: core.hash, timestamp: core.timestamp }
        }
    }

    impl From<fynd_core::Route> for Route {
        fn from(core: fynd_core::Route) -> Self {
            Route {
                swaps: core
                    .swaps
                    .into_iter()
                    .map(Into::into)
                    .collect(),
            }
        }
    }

    impl From<fynd_core::Swap> for Swap {
        fn from(core: fynd_core::Swap) -> Self {
            Swap {
                component_id: core.component_id,
                protocol: core.protocol,
                token_in: core.token_in,
                token_out: core.token_out,
                amount_in: core.amount_in,
                amount_out: core.amount_out,
                gas_estimate: core.gas_estimate,
            }
        }
    }

    #[cfg(test)]
    mod tests {
        use num_bigint::BigUint;
        use tycho_simulation::tycho_common::models::Address;

        use super::*;

        fn make_address(byte: u8) -> Address {
            Address::from([byte; 20])
        }

        #[test]
        fn test_solution_request_roundtrip() {
            let dto = SolutionRequest {
                orders: vec![Order {
                    id: "test-id".to_string(),
                    token_in: make_address(0x01),
                    token_out: make_address(0x02),
                    amount: BigUint::from(1000u64),
                    side: OrderSide::Sell,
                    sender: make_address(0xAA),
                    receiver: None,
                }],
                options: SolutionOptions {
                    timeout_ms: Some(5000),
                    min_responses: None,
                    max_gas: None,
                },
            };

            let core: fynd_core::SolutionRequest = dto.clone().into();
            assert_eq!(core.orders.len(), 1);
            assert_eq!(core.orders[0].id, "test-id");
            assert_eq!(core.options.timeout_ms, Some(5000));
        }

        #[test]
        fn test_solution_from_core() {
            let core = fynd_core::Solution {
                orders: vec![],
                total_gas_estimate: BigUint::from(100_000u64),
                solve_time_ms: 50,
            };

            let dto = Solution::from(core);
            assert_eq!(dto.total_gas_estimate, BigUint::from(100_000u64));
            assert_eq!(dto.solve_time_ms, 50);
        }

        #[test]
        fn test_order_side_into_core() {
            let core: fynd_core::OrderSide = OrderSide::Sell.into();
            assert_eq!(core, fynd_core::OrderSide::Sell);
        }

        #[test]
        fn test_solution_status_from_core() {
            let cases = [
                (fynd_core::SolutionStatus::Success, SolutionStatus::Success),
                (fynd_core::SolutionStatus::NoRouteFound, SolutionStatus::NoRouteFound),
                (
                    fynd_core::SolutionStatus::InsufficientLiquidity,
                    SolutionStatus::InsufficientLiquidity,
                ),
                (fynd_core::SolutionStatus::Timeout, SolutionStatus::Timeout),
                (fynd_core::SolutionStatus::NotReady, SolutionStatus::NotReady),
            ];

            for (core, expected) in cases {
                assert_eq!(SolutionStatus::from(core), expected);
            }
        }
    }
}
