//! API request and response types.

use num_bigint::BigUint;
use num_traits::Zero;
use serde::{Deserialize, Serialize};
use tycho_simulation::tycho_core::models::Address;
use uuid::Uuid;

/// Request to solve one or more swap orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SolutionRequest {
    /// Orders to solve.
    pub orders: Vec<Order>,
    /// Optional solving parameters. Global options that apply to all orders
    #[serde(default)]
    pub options: SolutionOptions,
}

/// Options to customize the solving behavior.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SolutionOptions {
    /// Timeout in milliseconds (if None, uses default).
    pub timeout_ms: Option<u64>,
}

/// A single swap order to be solved.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    /// Unique identifier for this order (auto-generated by the API, ignored if provided by client).
    #[serde(default = "generate_order_id")]
    pub id: String,
    /// Input token address (sell token).
    pub token_in: Address,
    /// Output token address (buy token).
    pub token_out: Address,
    /// Amount to swap.
    pub amount: BigUint,
    /// Order kind: sell or buy.
    pub kind: OrderKind,
    /// Address that will send the input tokens.
    pub sender: Address,
    /// Address that will receive the output tokens (if different from sender).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receiver: Option<Address>,
}

/// Generate a unique order ID.
fn generate_order_id() -> String {
    Uuid::new_v4().to_string()
}

/// Specifies what kind of order this is.
///
/// Currently only `Sell` is supported. `Buy` will be added in a future version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderKind {
    /// Sell exactly this amount of sell_token.
    Sell,
    // Future: Buy variant
    // /// Buy exactly this amount of buy_token.
    // Buy,
}

impl Order {
    /// Returns true if this is a sell order (exact input).
    pub fn is_sell(&self) -> bool {
        matches!(self.kind, OrderKind::Sell)
    }

    /// Returns the effective receiver address.
    pub fn effective_receiver(&self) -> Address {
        self.receiver
            .clone()
            .unwrap_or_else(|| self.sender.clone())
    }

    /// Validates the order structure.
    pub fn validate(&self) -> Result<(), OrderValidationError> {
        // Token addresses must be different
        if self.token_in == self.token_out {
            return Err(OrderValidationError::SameTokens);
        }

        // Amount must be non-zero
        if self.amount.is_zero() {
            return Err(OrderValidationError::ZeroAmount);
        }

        Ok(())
    }
}

/// Order validation errors.
#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderValidationError {
    #[error("token_in and token_out are the same")]
    SameTokens,
    #[error("amount is zero")]
    ZeroAmount,
}

/// Health check response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthStatus {
    /// Whether the service is healthy.
    pub healthy: bool,
    /// Time since last market update in milliseconds.
    pub last_update_ms: u64,
    /// Number of pending tasks in queue.
    pub queue_depth: usize,
}
