//! Public interfaces for the solve endpoint.
//!
//! This module defines all solution-related request and response types exposed to clients:
//!
//! ## Request Types
//! - [`SolutionRequest`] - Top-level request containing orders to solve
//! - [`Order`] - A single swap order with token pair and amount
//! - [`SolutionOptions`] - Optional parameters for solving behavior
//!
//! ## Response Types
//! - [`Solution`] - Top-level response with solutions for all orders
//! - [`OrderSolution`] - Solution for a single order including route
//! - [`Route`] - Sequence of swaps to execute
//! - [`Swap`] - A single swap on a specific protocol

use num_bigint::BigUint;
use num_traits::Zero;
use serde::{Deserialize, Serialize};
use tycho_simulation::tycho_core::models::Address;
use uuid::Uuid;

use super::primitives::{ComponentId, ProtocolSystem};

// ============================================================================
// REQUEST TYPES
// ============================================================================

/// Request to solve one or more swap orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SolutionRequest {
    /// Orders to solve.
    pub orders: Vec<Order>,
    /// Optional solving parameters that apply to all orders.
    #[serde(default)]
    pub options: SolutionOptions,
}

/// Options to customize the solving behavior.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SolutionOptions {
    /// Timeout in milliseconds. If `None`, uses server default.
    pub timeout_ms: Option<u64>,
}

/// A single swap order to be solved.
///
/// An order specifies an intent to swap one token for another.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    /// Unique identifier for this order.
    ///
    /// Auto-generated by the API.
    #[serde(default = "generate_order_id", skip_deserializing)]
    pub id: String,
    /// Input token address (the token being sold).
    pub token_in: Address,
    /// Output token address (the token being bought).
    pub token_out: Address,
    /// Amount to swap, interpreted according to `kind`.
    pub amount: BigUint,
    /// Whether this is a sell (exact input) or buy (exact output) order.
    pub kind: OrderKind,
    /// Address that will send the input tokens.
    pub sender: Address,
    /// Address that will receive the output tokens.
    ///
    /// Defaults to `sender` if not specified.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receiver: Option<Address>,
}

impl Order {
    /// Returns `true` if this is a sell order (exact input amount).
    pub fn is_sell(&self) -> bool {
        matches!(self.kind, OrderKind::Sell)
    }

    /// Returns the address that will receive the output tokens.
    ///
    /// Returns `receiver` if set, otherwise returns `sender`.
    pub fn effective_receiver(&self) -> Address {
        self.receiver
            .clone()
            .unwrap_or_else(|| self.sender.clone())
    }

    /// Validates the order structure.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - `token_in` and `token_out` are the same address
    /// - `amount` is zero
    pub fn validate(&self) -> Result<(), OrderValidationError> {
        if self.token_in == self.token_out {
            return Err(OrderValidationError::SameTokens);
        }

        if self.amount.is_zero() {
            return Err(OrderValidationError::ZeroAmount);
        }

        Ok(())
    }
}

/// Specifies whether an order is a sell (exact input) or buy (exact output).
///
/// Currently only `Sell` is supported. `Buy` will be added in a future version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderKind {
    /// Sell exactly the specified amount of the input token.
    Sell,
    // TODO: Add Buy variant for exact output orders
}

/// Errors that can occur when validating an [`Order`].
#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderValidationError {
    #[error("token_in and token_out must be different")]
    SameTokens,
    #[error("amount must be non-zero")]
    ZeroAmount,
}

// ============================================================================
// RESPONSE TYPES
// ============================================================================

/// Complete solution for a [`SolutionRequest`].
///
/// Contains a solution for each order in the request, along with aggregate
/// gas estimates and timing information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Solution {
    /// Solutions for each order, in the same order as the request.
    pub orders: Vec<OrderSolution>,
    /// Total estimated gas for executing all swaps.
    pub total_gas_estimate: BigUint,
    /// Time taken to compute this solution, in milliseconds.
    pub solve_time_ms: u64,
}

/// Solution for a single [`Order`].
///
/// Contains the route to execute (if found), along with expected amounts,
/// gas estimates, and status information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderSolution {
    /// ID of the order this solution corresponds to.
    pub order_id: String,
    /// Status indicating whether a route was found.
    pub status: SolutionStatus,
    /// The route to execute, if a valid route was found.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<Route>,
    /// Amount of input token.
    pub amount_in: BigUint,
    /// Amount of output token.
    pub amount_out: BigUint,
    /// Estimated gas cost for executing this route.
    pub gas_estimate: BigUint,
    /// Price impact in basis points (1 bp = 0.01%).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_impact_bps: Option<i32>,
    /// Block at which this quote was computed.
    pub block: BlockInfo,
    /// Algorithm that found this solution (internal use only).
    #[serde(skip)]
    pub algorithm: String,
}

/// Status of an order solution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SolutionStatus {
    /// A valid route was found.
    Success,
    /// No route exists between the specified tokens.
    NoRouteFound,
    /// A route exists but available liquidity is insufficient.
    InsufficientLiquidity,
    /// The solver timed out before finding a route.
    Timeout,
}

/// Block information at which a quote was computed.
///
/// Quotes are only valid for the block at which they were computed. Market
/// conditions may change in subsequent blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockInfo {
    /// Block number.
    pub number: u64,
    /// Block hash as a hex string.
    pub hash: String,
    /// Block timestamp in Unix seconds.
    pub timestamp: u64,
}

// ============================================================================
// ROUTE & SWAP TYPES
// ============================================================================

/// A route consisting of one or more sequential swaps.
///
/// A route describes the path through liquidity pools to execute a swap.
/// For multi-hop swaps, the output of each swap becomes the input of the next.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Route {
    /// Ordered sequence of swaps to execute.
    pub swaps: Vec<Swap>,
}

impl Route {
    /// Creates a new route from a list of swaps.
    pub fn new(swaps: Vec<Swap>) -> Self {
        Self { swaps }
    }

    /// Returns the number of hops (swaps) in this route.
    pub fn hop_count(&self) -> usize {
        self.swaps.len()
    }

    /// Returns the input token of the route (first swap's input).
    pub fn input_token(&self) -> Option<Address> {
        self.swaps.first().map(|s| s.token_in.clone())
    }

    /// Returns the output token of the route (last swap's output).
    pub fn output_token(&self) -> Option<Address> {
        self.swaps.last().map(|s| s.token_out.clone())
    }

    /// Returns intermediate tokens (excluding input and output).
    pub fn intermediate_tokens(&self) -> Vec<Address> {
        if self.swaps.len() <= 1 {
            return vec![];
        }

        self.swaps[..self.swaps.len() - 1]
            .iter()
            .map(|s| s.token_out.clone())
            .collect()
    }

    /// Returns the total gas estimate for all swaps in this route.
    pub fn total_gas(&self) -> BigUint {
        self.swaps
            .iter()
            .map(|s| &s.gas_estimate)
            .fold(BigUint::ZERO, |acc, g| acc + g)
    }

    /// Validates that the route is well-formed.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The route has no swaps
    /// - Consecutive swaps are not connected (output token != next input token)
    pub fn validate(&self) -> Result<(), RouteValidationError> {
        if self.swaps.is_empty() {
            return Err(RouteValidationError::EmptyRoute);
        }

        for window in self.swaps.windows(2) {
            if window[0].token_out != window[1].token_in {
                return Err(RouteValidationError::DisconnectedSwaps {
                    first_out: window[0].token_out.clone(),
                    second_in: window[1].token_in.clone(),
                });
            }
        }

        Ok(())
    }
}

/// Errors that can occur when validating a [`Route`].
#[derive(Debug, Clone, thiserror::Error)]
pub enum RouteValidationError {
    #[error("route must contain at least one swap")]
    EmptyRoute,
    #[error("swaps are not connected: {first_out} != {second_in}")]
    DisconnectedSwaps {
        first_out: Address,
        second_in: Address,
    },
}

/// A single swap within a route.
///
/// Represents an atomic swap on a specific liquidity pool (component).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Swap {
    /// Identifier of the liquidity pool component.
    pub component_id: ComponentId,
    /// Protocol system (e.g., Uniswap V2, Uniswap V3, Balancer).
    pub protocol: ProtocolSystem,
    /// Input token address.
    pub token_in: Address,
    /// Output token address.
    pub token_out: Address,
    /// Amount of input token.
    pub amount_in: BigUint,
    /// Amount of output token.
    pub amount_out: BigUint,
    /// Estimated gas cost for this swap.
    pub gas_estimate: BigUint,
}

impl Swap {
    /// Creates a new swap with an auto-calculated gas estimate.
    pub fn new(
        component_id: ComponentId,
        protocol: ProtocolSystem,
        token_in: Address,
        token_out: Address,
        amount_in: BigUint,
        amount_out: BigUint,
    ) -> Self {
        let gas_estimate = BigUint::from(protocol.typical_gas_cost());
        Self {
            component_id,
            protocol,
            token_in,
            token_out,
            amount_in,
            amount_out,
            gas_estimate,
        }
    }
}

// ============================================================================
// PRIVATE HELPERS
// ============================================================================

/// Generates a unique order ID using UUID v4.
fn generate_order_id() -> String {
    Uuid::new_v4().to_string()
}
