//! Public interfaces for the solve endpoint.
//!
//! This module defines all solution-related request and response types exposed to clients:
//!
//! ## Request Types
//! - [`SolutionRequest`] - Top-level request containing orders to solve
//! - [`Order`] - A single swap order with token pair and amount
//! - [`SolutionOptions`] - Optional parameters for solving behavior
//!
//! ## Response Types
//! - [`Solution`] - Top-level response with solutions for all orders
//! - [`OrderSolution`] - Solution for a single order including route
//! - [`Route`] - Sequence of swaps to execute
//! - [`Swap`] - A single swap on a specific protocol

use num_bigint::BigUint;
use num_traits::Zero;
use serde::{Deserialize, Serialize};
use tycho_simulation::tycho_core::models::Address;
use uuid::Uuid;

use super::{
    primitives::{ComponentId, ProtocolSystem},
    serde_helpers::biguint_as_string,
};

// ============================================================================
// REQUEST TYPES
// ============================================================================

/// Request to solve one or more swap orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SolutionRequest {
    /// Orders to solve.
    pub orders: Vec<Order>,
    /// Optional solving parameters that apply to all orders.
    #[serde(default)]
    pub options: SolutionOptions,
}

/// Options to customize the solving behavior.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SolutionOptions {
    /// Timeout in milliseconds. If `None`, uses server default.
    pub timeout_ms: Option<u64>,
}

/// A single swap order to be solved.
///
/// An order specifies an intent to swap one token for another.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    /// Unique identifier for this order.
    ///
    /// Auto-generated by the API.
    #[serde(default = "generate_order_id", skip_deserializing)]
    pub id: String,
    /// Input token address (the token being sold).
    pub token_in: Address,
    /// Output token address (the token being bought).
    pub token_out: Address,
    /// Amount to swap, interpreted according to `kind` (in token units, as decimal string).
    #[serde(with = "biguint_as_string")]
    pub amount: BigUint,
    /// Whether this is a sell (exact input) or buy (exact output) order.
    pub kind: OrderKind,
    /// Address that will send the input tokens.
    pub sender: Address,
    /// Address that will receive the output tokens.
    ///
    /// Defaults to `sender` if not specified.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receiver: Option<Address>,
}

impl Order {
    /// Returns `true` if this is a sell order (exact input amount).
    pub fn is_sell(&self) -> bool {
        matches!(self.kind, OrderKind::Sell)
    }

    /// Returns the address that will receive the output tokens.
    ///
    /// Returns `receiver` if set, otherwise returns `sender`.
    pub fn effective_receiver(&self) -> Address {
        self.receiver
            .clone()
            .unwrap_or_else(|| self.sender.clone())
    }

    /// Validates the order structure.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - `token_in` and `token_out` are the same address
    /// - `amount` is zero
    pub fn validate(&self) -> Result<(), OrderValidationError> {
        if self.token_in == self.token_out {
            return Err(OrderValidationError::SameTokens);
        }

        if self.amount.is_zero() {
            return Err(OrderValidationError::ZeroAmount);
        }

        Ok(())
    }
}

/// Specifies whether an order is a sell (exact input) or buy (exact output).
///
/// Currently only `Sell` is supported. `Buy` will be added in a future version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderKind {
    /// Sell exactly the specified amount of the input token.
    Sell,
    // TODO: Add Buy variant for exact output orders
}

/// Errors that can occur when validating an [`Order`].
#[derive(Debug, Clone, thiserror::Error)]
pub enum OrderValidationError {
    #[error("token_in and token_out must be different")]
    SameTokens,
    #[error("amount must be non-zero")]
    ZeroAmount,
}

// ============================================================================
// RESPONSE TYPES
// ============================================================================

/// Complete solution for a [`SolutionRequest`].
///
/// Contains a solution for each order in the request, along with aggregate
/// gas estimates and timing information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Solution {
    /// Solutions for each order, in the same order as the request.
    pub orders: Vec<OrderSolution>,
    /// Total estimated gas for executing all swaps (as decimal string).
    #[serde(with = "biguint_as_string")]
    pub total_gas_estimate: BigUint,
    /// Time taken to compute this solution, in milliseconds.
    pub solve_time_ms: u64,
}

/// Solution for a single [`Order`].
///
/// Contains the route to execute (if found), along with expected amounts,
/// gas estimates, and status information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderSolution {
    /// ID of the order this solution corresponds to.
    pub order_id: String,
    /// Status indicating whether a route was found.
    pub status: SolutionStatus,
    /// The route to execute, if a valid route was found.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<Route>,
    /// Amount of input token (in token units, as decimal string).
    #[serde(with = "biguint_as_string")]
    pub amount_in: BigUint,
    /// Amount of output token (in token units, as decimal string).
    #[serde(with = "biguint_as_string")]
    pub amount_out: BigUint,
    /// Estimated gas cost for executing this route (as decimal string).
    #[serde(with = "biguint_as_string")]
    pub gas_estimate: BigUint,
    /// Price impact in basis points (1 bp = 0.01%).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_impact_bps: Option<i32>,
    /// Block at which this quote was computed.
    pub block: BlockInfo,
    /// Algorithm that found this solution (internal use only).
    #[serde(skip)]
    pub algorithm: String,
}

/// Status of an order solution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SolutionStatus {
    /// A valid route was found.
    Success,
    /// No route exists between the specified tokens.
    NoRouteFound,
    /// A route exists but available liquidity is insufficient.
    InsufficientLiquidity,
    /// The solver timed out before finding a route.
    Timeout,
}

/// Block information at which a quote was computed.
///
/// Quotes are only valid for the block at which they were computed. Market
/// conditions may change in subsequent blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockInfo {
    /// Block number.
    pub number: u64,
    /// Block hash as a hex string.
    pub hash: String,
    /// Block timestamp in Unix seconds.
    pub timestamp: u64,
}

// ============================================================================
// ROUTE & SWAP TYPES
// ============================================================================

/// A route consisting of one or more sequential swaps.
///
/// A route describes the path through liquidity pools to execute a swap.
/// For multi-hop swaps, the output of each swap becomes the input of the next.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Route {
    /// Ordered sequence of swaps to execute.
    pub swaps: Vec<Swap>,
}

impl Route {
    /// Creates a new route from a list of swaps.
    pub fn new(swaps: Vec<Swap>) -> Self {
        Self { swaps }
    }

    /// Returns the number of hops (swaps) in this route.
    pub fn hop_count(&self) -> usize {
        self.swaps.len()
    }

    /// Returns the input token of the route (first swap's input).
    pub fn input_token(&self) -> Option<Address> {
        self.swaps
            .first()
            .map(|s| s.token_in.clone())
    }

    /// Returns the output token of the route (last swap's output).
    pub fn output_token(&self) -> Option<Address> {
        self.swaps
            .last()
            .map(|s| s.token_out.clone())
    }

    /// Returns intermediate tokens (excluding input and output).
    pub fn intermediate_tokens(&self) -> Vec<Address> {
        if self.swaps.len() <= 1 {
            return vec![];
        }

        self.swaps[..self.swaps.len() - 1]
            .iter()
            .map(|s| s.token_out.clone())
            .collect()
    }

    /// Returns the total gas estimate for all swaps in this route.
    pub fn total_gas(&self) -> BigUint {
        self.swaps
            .iter()
            .map(|s| &s.gas_estimate)
            .fold(BigUint::ZERO, |acc, g| acc + g)
    }

    /// Validates that the route is well-formed.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The route has no swaps
    /// - Consecutive swaps are not connected (output token != next input token)
    pub fn validate(&self) -> Result<(), RouteValidationError> {
        if self.swaps.is_empty() {
            return Err(RouteValidationError::EmptyRoute);
        }

        for window in self.swaps.windows(2) {
            if window[0].token_out != window[1].token_in {
                return Err(RouteValidationError::DisconnectedSwaps {
                    first_out: window[0].token_out.clone(),
                    second_in: window[1].token_in.clone(),
                });
            }
        }

        Ok(())
    }
}

/// Errors that can occur when validating a [`Route`].
#[derive(Debug, Clone, thiserror::Error)]
pub enum RouteValidationError {
    #[error("route must contain at least one swap")]
    EmptyRoute,
    #[error("swaps are not connected: {first_out} != {second_in}")]
    DisconnectedSwaps { first_out: Address, second_in: Address },
}

/// A single swap within a route.
///
/// Represents an atomic swap on a specific liquidity pool (component).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Swap {
    /// Identifier of the liquidity pool component.
    pub component_id: ComponentId,
    /// Protocol system (e.g., Uniswap V2, Uniswap V3, Balancer).
    pub protocol: ProtocolSystem,
    /// Input token address.
    pub token_in: Address,
    /// Output token address.
    pub token_out: Address,
    /// Amount of input token (in token units, as decimal string).
    #[serde(with = "biguint_as_string")]
    pub amount_in: BigUint,
    /// Amount of output token (in token units, as decimal string).
    #[serde(with = "biguint_as_string")]
    pub amount_out: BigUint,
    /// Estimated gas cost for this swap (as decimal string).
    #[serde(with = "biguint_as_string")]
    pub gas_estimate: BigUint,
}

impl Swap {
    /// Creates a new swap with an auto-calculated gas estimate.
    pub fn new(
        component_id: ComponentId,
        protocol: ProtocolSystem,
        token_in: Address,
        token_out: Address,
        amount_in: BigUint,
        amount_out: BigUint,
    ) -> Self {
        let gas_estimate = BigUint::from(protocol.typical_gas_cost());
        Self { component_id, protocol, token_in, token_out, amount_in, amount_out, gas_estimate }
    }
}

// ============================================================================
// PRIVATE HELPERS
// ============================================================================

/// Generates a unique order ID using UUID v4.
fn generate_order_id() -> String {
    Uuid::new_v4().to_string()
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;

    fn make_address(byte: u8) -> Address {
        Address::from([byte; 20])
    }

    fn make_order(token_in_byte: u8, token_out_byte: u8, amount: u64) -> Order {
        Order {
            id: generate_order_id(),
            token_in: make_address(token_in_byte),
            token_out: make_address(token_out_byte),
            amount: BigUint::from(amount),
            kind: OrderKind::Sell,
            sender: make_address(0xAA),
            receiver: None,
        }
    }

    fn make_swap(token_in_byte: u8, token_out_byte: u8, amount_in: u64, amount_out: u64) -> Swap {
        Swap {
            component_id: "pool-1".to_string(),
            protocol: ProtocolSystem::UniswapV2,
            token_in: make_address(token_in_byte),
            token_out: make_address(token_out_byte),
            amount_in: BigUint::from(amount_in),
            amount_out: BigUint::from(amount_out),
            gas_estimate: BigUint::from(100_000u64),
        }
    }

    // -------------------------------------------------------------------------
    // Order Tests
    // -------------------------------------------------------------------------

    #[test]
    fn test_order_is_sell() {
        let order = make_order(0x01, 0x02, 1000);
        assert!(order.is_sell());
    }

    #[rstest]
    #[case::with_receiver(Some(0xBB), 0xBB)]
    #[case::without_receiver(None, 0xAA)]
    fn test_order_effective_receiver(#[case] receiver: Option<u8>, #[case] expected: u8) {
        let mut order = make_order(0x01, 0x02, 1000);
        order.receiver = receiver.map(make_address);
        assert_eq!(order.effective_receiver(), make_address(expected));
    }

    #[rstest]
    #[case::valid(0x01, 0x02, 1000, true, None)]
    #[case::same_tokens(0x01, 0x01, 1000, false, Some("SameTokens"))]
    #[case::zero_amount(0x01, 0x02, 0, false, Some("ZeroAmount"))]
    fn test_order_validation(
        #[case] token_in: u8,
        #[case] token_out: u8,
        #[case] amount: u64,
        #[case] should_pass: bool,
        #[case] error_type: Option<&str>,
    ) {
        let order = make_order(token_in, token_out, amount);
        let result = order.validate();

        assert_eq!(result.is_ok(), should_pass);
        if let Some(err_name) = error_type {
            let err = result.unwrap_err();
            match err_name {
                "SameTokens" => assert!(matches!(err, OrderValidationError::SameTokens)),
                "ZeroAmount" => assert!(matches!(err, OrderValidationError::ZeroAmount)),
                _ => panic!("Unknown error type"),
            }
        }
    }

    #[test]
    fn test_order_id_auto_generated() {
        let id = generate_order_id();
        assert!(!id.is_empty());
        assert!(id.contains('-')); // UUIDs contain dashes
    }

    // -------------------------------------------------------------------------
    // Route Tests
    // -------------------------------------------------------------------------

    #[rstest]
    #[case::empty(vec![], 0)]
    #[case::single(vec![(0x01, 0x02)], 1)]
    #[case::two_hops(vec![(0x01, 0x02), (0x02, 0x03)], 2)]
    #[case::three_hops(vec![(0x01, 0x02), (0x02, 0x03), (0x03, 0x04)], 3)]
    fn test_route_hop_count(#[case] swaps: Vec<(u8, u8)>, #[case] expected: usize) {
        let route = Route::new(
            swaps
                .into_iter()
                .map(|(a, b)| make_swap(a, b, 1000, 990))
                .collect(),
        );
        assert_eq!(route.hop_count(), expected);
    }

    #[rstest]
    #[case::empty(vec![], None)]
    #[case::single(vec![(0x01, 0x02)], Some(0x01))]
    #[case::multi(vec![(0x01, 0x02), (0x02, 0x03)], Some(0x01))]
    fn test_route_input_token(#[case] swaps: Vec<(u8, u8)>, #[case] expected: Option<u8>) {
        let route = Route::new(
            swaps
                .into_iter()
                .map(|(a, b)| make_swap(a, b, 1000, 990))
                .collect(),
        );
        assert_eq!(route.input_token(), expected.map(make_address));
    }

    #[rstest]
    #[case::empty(vec![], None)]
    #[case::single(vec![(0x01, 0x02)], Some(0x02))]
    #[case::multi(vec![(0x01, 0x02), (0x02, 0x03)], Some(0x03))]
    fn test_route_output_token(#[case] swaps: Vec<(u8, u8)>, #[case] expected: Option<u8>) {
        let route = Route::new(
            swaps
                .into_iter()
                .map(|(a, b)| make_swap(a, b, 1000, 990))
                .collect(),
        );
        assert_eq!(route.output_token(), expected.map(make_address));
    }

    #[rstest]
    #[case::empty(vec![], vec![])]
    #[case::single(vec![(0x01, 0x02)], vec![])]
    #[case::two_hops(vec![(0x01, 0x02), (0x02, 0x03)], vec![0x02])]
    #[case::three_hops(vec![(0x01, 0x02), (0x02, 0x03), (0x03, 0x04)], vec![0x02, 0x03])]
    fn test_route_intermediate_tokens(#[case] swaps: Vec<(u8, u8)>, #[case] expected: Vec<u8>) {
        let route = Route::new(
            swaps
                .into_iter()
                .map(|(a, b)| make_swap(a, b, 1000, 990))
                .collect(),
        );
        let intermediates = route.intermediate_tokens();
        assert_eq!(
            intermediates,
            expected
                .into_iter()
                .map(make_address)
                .collect::<Vec<_>>()
        );
    }

    #[rstest]
    #[case::empty(0, 0u64)]
    #[case::single(1, 100_000u64)]
    #[case::two_swaps(2, 200_000u64)]
    #[case::three_swaps(3, 300_000u64)]
    fn test_route_total_gas(#[case] num_swaps: usize, #[case] expected_gas: u64) {
        let swaps: Vec<Swap> = (0..num_swaps)
            .map(|i| make_swap(i as u8, (i + 1) as u8, 1000, 990))
            .collect();
        let route = Route::new(swaps);
        assert_eq!(route.total_gas(), BigUint::from(expected_gas));
    }

    #[rstest]
    #[case::valid_single(vec![(0x01, 0x02)], true, None)]
    #[case::valid_connected(vec![(0x01, 0x02), (0x02, 0x03)], true, None)]
    #[case::empty(vec![], false, Some("EmptyRoute"))]
    #[case::disconnected(vec![(0x01, 0x02), (0x03, 0x04)], false, Some("DisconnectedSwaps"))]
    fn test_route_validation(
        #[case] swaps: Vec<(u8, u8)>,
        #[case] should_pass: bool,
        #[case] error_type: Option<&str>,
    ) {
        let route = Route::new(
            swaps
                .into_iter()
                .map(|(a, b)| make_swap(a, b, 1000, 990))
                .collect(),
        );
        let result = route.validate();

        assert_eq!(result.is_ok(), should_pass);
        if let Some(err_name) = error_type {
            let err = result.unwrap_err();
            match err_name {
                "EmptyRoute" => assert!(matches!(err, RouteValidationError::EmptyRoute)),
                "DisconnectedSwaps" => {
                    assert!(matches!(err, RouteValidationError::DisconnectedSwaps { .. }))
                }
                _ => panic!("Unknown error type"),
            }
        }
    }

    // -------------------------------------------------------------------------
    // Serialization Tests - BigUint as String
    // -------------------------------------------------------------------------

    #[test]
    fn test_order_serializes_amount_as_string() {
        let order = make_order(0x01, 0x02, 1_000_000_000_000_000_000);
        let json = serde_json::to_string(&order).unwrap();

        assert!(json.contains(r#""amount":"1000000000000000000""#));
        assert!(!json.contains(r#""amount":1000000000000000000"#));
    }

    #[test]
    fn test_order_deserializes_amount_from_string() {
        let json = r#"{
            "token_in": "0x0101010101010101010101010101010101010101",
            "token_out": "0x0202020202020202020202020202020202020202",
            "amount": "1000000000000000000",
            "kind": "sell",
            "sender": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        }"#;

        let order: Order = serde_json::from_str(json).unwrap();
        assert_eq!(order.amount, BigUint::from(1_000_000_000_000_000_000u64));
    }

    #[test]
    fn test_swap_serializes_amounts_as_strings() {
        let swap = make_swap(0x01, 0x02, 1_000_000_000, 999_000_000);
        let json = serde_json::to_string(&swap).unwrap();

        assert!(json.contains(r#""amount_in":"1000000000""#));
        assert!(json.contains(r#""amount_out":"999000000""#));
        assert!(json.contains(r#""gas_estimate":"100000""#));
    }

    #[test]
    fn test_swap_deserializes_amounts_from_strings() {
        let json = r#"{
            "component_id": "pool-1",
            "protocol": "uniswap_v2",
            "token_in": "0x0101010101010101010101010101010101010101",
            "token_out": "0x0202020202020202020202020202020202020202",
            "amount_in": "1000000000000000000",
            "amount_out": "999000000000000000",
            "gas_estimate": "150000"
        }"#;

        let swap: Swap = serde_json::from_str(json).unwrap();
        assert_eq!(swap.amount_in, BigUint::from(1_000_000_000_000_000_000u64));
        assert_eq!(swap.amount_out, BigUint::from(999_000_000_000_000_000u64));
        assert_eq!(swap.gas_estimate, BigUint::from(150_000u64));
    }

    #[test]
    fn test_large_amounts_serialize_correctly() {
        // 2^256 - 1, larger than JS safe integer (2^53 - 1)
        let large_amount = BigUint::parse_bytes(
            b"115792089237316195423570985008687907853269984665640564039457584007913129639935",
            10,
        )
        .unwrap();

        let order = Order {
            id: "test".to_string(),
            token_in: make_address(0x01),
            token_out: make_address(0x02),
            amount: large_amount.clone(),
            kind: OrderKind::Sell,
            sender: make_address(0xAA),
            receiver: None,
        };

        let json = serde_json::to_string(&order).unwrap();
        assert!(json.contains(
            r#""amount":"115792089237316195423570985008687907853269984665640564039457584007913129639935""#
        ));

        // Round-trip preserves value
        let deserialized: Order = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.amount, large_amount);
    }

    #[test]
    fn test_solution_serializes_amounts_as_strings() {
        let solution = Solution {
            orders: vec![],
            total_gas_estimate: BigUint::from(500_000u64),
            solve_time_ms: 10,
        };

        let json = serde_json::to_string(&solution).unwrap();
        assert!(json.contains(r#""total_gas_estimate":"500000""#));
    }
}
